conditioning:
#  method: ps
  method: DSG
#  method: ours
  params:
    scale: 0.5
    step_size: 0.5
    interval: 10

data:
  name: ffhq
  root: ./data/samples/
#  root: ./data/imagenet_test/
#  root: ./data/animal/


measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    # mask_len_range: !!python/tuple [128, 129]  # for box
    mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.05
