sampler: ddim
steps: 1000
noise_schedule: linear
model_mean_type: epsilon 
model_var_type: learned_range
dynamic_threshold: False
clip_denoised: True
rescale_timesteps: True
timestep_respacing: 50
#eta: 1